/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        int[] result = roll(4);
        for(int c = 0; c < result.length; c+=1){
            System.out.println(result[c]);
        }
        boolean isDuplicate = containsDuplicates(result);
        System.out.println(isDuplicate);
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        for(int i = 0; i < weeklyMonthTemperatures.length; i+=1){
            System.out.println(calculateAvarage(weeklyMonthTemperatures[i]));
        }
    }

    public static int[] roll(int n){
        int[] result = new int[n];
        for(int i = 0; i < n; i+=1){
            result[i] = (int)Math.floor(Math.random()*(6-1+1)+1);
        }
        return result;
    }

    public static boolean containsDuplicates(int[] arr){
        for(int i = 0; i < arr.length; i+=1){
            for(int c = 0; c < arr.length; c+=1){
                if (i != c && arr[i] == arr[c]){
                    return true;
                }
            }
        }
        return false;
    }

    public static float calculateAvarage(int[] arr){
        float avg = 0.0f;
        for(int i = 0; i < arr.length; i+=1){
            avg += arr[i];
        }
        return avg/arr.length;
    }

}




